name: polka_module
description: A new Flutter module.
publish_to: "none"
version: 3.2.4+3242

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.0.1
  #  json_annotation: ^3.1.1
  get_storage: ^2.0.2
  biometric_storage: ^2.0.2
  update_app: ^0.1.7
  device_info: ^2.0.1
  uni_links: ^0.5.1
  fl_chart: ^0.40.5
  flutter_boost:
    git:
      url: https://github.com/alibaba/flutter_boost.git
      ref: bf12730c4108d23e03cb5bca38a34afaf61dc445
  # firebase_core: 1.5.0
  # firebase_analytics: 8.3.0
  flutter_screenutil: ^5.0.0+2
  #  firebase_messaging: 10.0.5
  polkawallet_plugin_kusama:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_kusama.git
      ref: e9e7c2546a1a6241c55a064d2fa57987a9265051
  polkawallet_plugin_chainx:
    git:
      url: https://github.com/chainx-org/polkawallet_plugin_chainx.git
      ref: 2cc634bc4f0b873e7fe0801d5d3fba46756f5315
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  # flutter_bugly: ^0.4.3
  # flutter_bugly_play:
  #   git:
  #     url: https://github.com/polkawallet-io/flutter_bugly.git
  #     ref: da653ff78e269d011d1224e368e70703794601a1
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  card_swiper: ^2.0.3
  package_info: ^2.0.2
  simple_shadow: ^0.2.0
  liquid_progress_indicator: ^0.4.0

dependency_overrides:
  flutter_boost:
    path: ../coding/flutter_boost
  polkawallet_plugin_kusama:
    path: ../coding/polkawallet/polkawallet_plugin_kusama
  polkawallet_plugin_karura:
    path: ../coding/polkawallet/polkawallet_plugin_karura
  polkawallet_plugin_chainx:
    path: ../coding/polkawallet/polkawallet_plugin_chainx
  #  polkawallet_plugin_bifrost:
  #    path: ../../coding/polkawallet/polkawallet_plugin_bifrost
  #  polkawallet_plugin_laminar:
  #    path: ../../coding/polkawallet/polkawallet_plugin_laminar
  #  polkawallet_plugin_chainx:
  #    path: ../../coding/polkawallet/polkawallet_plugin_chainx
  #  polkawallet_plugin_edgeware:
  #    path: ../../coding/polkawallet/polkawallet_plugin_edgeware
  # polkawallet_ui: ^0.3.4
  polkawallet_ui:
    #     path: ../../coding/polkawallet/ui
    #    git:
    #      url: https://github.com/polkawallet-io/ui.git
    #      ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5
    path: ../coding/polkawallet/ui
  #  polkawallet_sdk: ^0.3.0
  polkawallet_sdk:
    path: ../coding/polkawallet/sdk
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  liquid_progress_indicator: ^0.4.0
  webview_flutter: ^3.0.0
  flutter_markdown: ^0.6.9+1
  cached_network_image: ^3.2.0
  flutter_html: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  #  build_runner: ^1.10.9
  #  mobx_codegen: ^1.1.1
  #  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.9.0
  rive: ^0.7.33

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/public/
    - assets/images/icons/
    - assets/images/plugins/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.otf
          weight: 700
    - family: TitilliumWeb
      fonts:
        - asset: assets/fonts/TitilliumWeb-SemiBold.ttf
        - asset: assets/fonts/TitilliumWeb-Black.ttf
        - asset: assets/fonts/TitilliumWeb-Bold.ttf
        - asset: assets/fonts/TitilliumWeb-BoldItalic.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLight.ttf
        - asset: assets/fonts/TitilliumWeb-ExtraLightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Italic.ttf
        - asset: assets/fonts/TitilliumWeb-Light.ttf
        - asset: assets/fonts/TitilliumWeb-LightItalic.ttf
        - asset: assets/fonts/TitilliumWeb-Regular.ttf
        - asset: assets/fonts/TitilliumWeb-SemiBoldItalic.ttf
    - family: SF_Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
  module:
    androidX: true
    androidPackage: com.bitpie
    iosBundleIdentifier: com.bitpie
