name: polka_module
description: A new Flutter module.
publish_to: "none"
version: 2.3.9+2392
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1
  json_annotation: ^4.0.1
  #  json_annotation: ^3.1.1
  get_storage: ^2.0.2
  biometric_storage: ^2.0.2
  update_app: ^0.1.7
  device_info: ^2.0.1
  uni_links: ^0.5.1
  flutter_boost:
    git:
      url: https://github.com/alibaba/flutter_boost.git
      ref: bf12730c4108d23e03cb5bca38a34afaf61dc445
  # firebase_core: 1.5.0
  # firebase_analytics: 8.3.0
  flutter_screenutil: ^5.0.0+2
  #  firebase_messaging: 10.0.5
  polkawallet_plugin_kusama:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_kusama.git
      ref: e9e7c2546a1a6241c55a064d2fa57987a9265051
  polkawallet_plugin_acala:
    git:
      url: https://github.com/AcalaNetwork/polkawallet_plugin_acala.git
      ref: 4e9f4f714666a5e6214fff9e5a89df03d62b756b
  polkawallet_plugin_karura:
    git:
      url: https://github.com/AcalaNetwork/polkawallet_plugin_karura.git
      ref: a4a86b310b94fd14714fc8067fc1a7c86c445dd4
  polkawallet_plugin_statemine:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_statemine.git
      ref: 7d8cf727c5eb78d97205e53fe2ade55c513754a9
  polkawallet_plugin_laminar:
    git:
      url: https://github.com/polkawallet-io/polkawallet_plugin_laminar.git
      ref: 7950c74abe74494aed49662b37dcebdacf1013c1
  polkawallet_plugin_bifrost:
    git:
      url: https://github.com/bifrost-finance/polkawallet_plugin_bifrost.git
      ref: 28fdd7e3d7e66e6fbe31bdbae3b09d88627e51b6
  polkawallet_plugin_chainx:
    git:
      url: https://github.com/chainx-org/polkawallet_plugin_chainx.git
      ref: a4a1d472e06822b22ccc25287405fba2048fe6e8
  polkawallet_plugin_edgeware:
    git:
      url: https://github.com/remzrn/polkawallet_plugin_edgeware.git
      ref: 11be316dc77b721d41ed6774fbf8d444a5a8eaa9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dependency_overrides:
  flutter_boost:
    path: ../coding/flutter_boost
  polkawallet_plugin_kusama:
    path: ../coding/polkawallet/polkawallet_plugin_kusama
  # polkawallet_plugin_acala:
  #   path: ../coding/polkawallet/polkawallet_plugin_acala
  polkawallet_plugin_karura:
    path: ../coding/polkawallet/polkawallet_plugin_karura
  #  polkawallet_plugin_bifrost:
  #    path: ../../coding/polkawallet/polkawallet_plugin_bifrost
  #  polkawallet_plugin_laminar:
  #    path: ../../coding/polkawallet/polkawallet_plugin_laminar
  #  polkawallet_plugin_statemine:
  #    path: ../../coding/polkawallet/polkawallet_plugin_statemine
  #  polkawallet_plugin_chainx:
  #    path: ../../coding/polkawallet/polkawallet_plugin_chainx
  #  polkawallet_plugin_edgeware:
  #    path: ../../coding/polkawallet/polkawallet_plugin_edgeware
  # polkawallet_ui: ^0.3.4
  polkawallet_ui:
    #     path: ../../coding/polkawallet/ui
    #    git:
    #      url: https://github.com/polkawallet-io/ui.git
    #      ref: 485a9cde97f2446d74a1aeb6d8d63e33683461a5
    path: ../coding/polkawallet/ui
  #  polkawallet_sdk: ^0.3.0
  polkawallet_sdk:
    path: ../coding/polkawallet/sdk
  charts_flutter:
    git:
      url: https://github.com/google/charts
      path: charts_flutter
  flutter_mobx: ^2.0.0
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3
  json_serializable: ^4.1.2
  #  build_runner: ^1.10.9
  #  mobx_codegen: ^1.1.1
  #  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/public/

  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue.otf
          weight: 700

  module:
    androidX: true
    androidPackage: com.bitpie
    iosBundleIdentifier: com.bitpie
